db:
    image: postgres:9.6.1
    environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=password
        - POSTGRES_ROOT_PASSWORD=root_password
    ports:
        - "5433:5432"

keycloak:
    image: keycloak_image:2.5.1.Final
    environment:
        - KEYCLOAK_LOGLEVEL=DEBUG
    links:
        - db:postgres
    ports:
        - "8089:8080"
        - "9999:9990"
        - "443:8443"
    volumes:
        - ./data:/data
