db:
    image: postgres
    environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=password
        - POSTGRES_ROOT_PASSWORD=root_password

keycloak:
    image: keycloak_image:1.7.0.Final
    environment:
        - KEYCLOAK_LOGLEVEL=DEBUG
    links:
        - db:postgres
    ports:
        - "8089:8080"
        - "9999:9990"
        - "443:8443"
    volumes:
        - ./data:/data
